# Numpy cheatsheet
_Gilbert François Duivesteijn_

---
**Work in progress.**

---

In [1]:
import numpy as np

eps = np.finfo(float).eps

## Overview

https://numpy.org/doc/stable/user/numpy-for-matlab-users.html

https://www.delftstack.com/howto/numpy/numpy-dot-vs-matmul/


| math notation | matlab command | numpy command             | remark |
| :------------ | :----------- |:----------- | :------------ |
| $C=A \cdot B$ | `A*B` | `A@B` | matrix operation |
|  |  | `np.matmul(A, B)` | matrix operation |
|  |  | `np.dot(A, B)` | matrix operation |
| $C=A \odot B$ |`A.*B`| `A*B` | element-wise operation |
| $C=A^2$ | `A.^2` | `A**2` | element-wise operation |
|  | | `np.square(A)` | element-wise operation |
| $C = A \otimes B$ | `kron(A, B)` | `np.kron(A, B)` | matrix operation |
| $\int\frac{\partial f}{\partial t}dt$ | `ode45` | `integrate.solve_ivp(f)` | integrate an ODE with Runge-Kutta 4,5 |

## Matrix product (matrix - matrix)

\begin{align}
C = A \cdot B
\end{align}

Use `@`, `np.dot` or `np.matmul` in numpy. For 2D matrices, they all give the same results. For $\mathbb{R}^n$ where $n>2$, the `@` operator and `np.matmul` give the same results, but `np.dot` has a slightly different implementation. The `np.matmul` function broadcasts the array like a stack of matrices as elements residing in the last two indexes, respectively. The `np.dot` function, on the other hand, performs multiplication as the sum of products over the last axis of the first array and the second-to-last of the second.

In [2]:
A = np.arange(0, 12).reshape(4, 3)
B = np.arange(0, 12).reshape(3, 4)
print("A= "); print(A)
print("B= "); print(B)

A= 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
B= 
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [3]:
C1 = A@B
C2 = np.matmul(A, B)
C3 = np.dot(A, B)

assert np.allclose(C1, C2)
assert np.allclose(C1, C3)
print("C= "); print(C3)

C= 
[[ 20  23  26  29]
 [ 56  68  80  92]
 [ 92 113 134 155]
 [128 158 188 218]]


In [4]:
a = np.random.rand(2, 2, 3)
b = np.random.rand(2, 3, 2)
cn = a@b

c0 = a[0]@b[0]
c1 = a[1]@b[1]
c2 = np.dot(a, b)

assert np.allclose(cn[0], c0)
assert np.allclose(cn[1], c1)

print(cn)
print(c0)
print(c1)

print()
print(c2)

[[[0.73360585 0.66861821]
  [0.81106372 0.73118198]]

 [[0.38135421 0.69572593]
  [0.63159265 0.7650871 ]]]
[[0.73360585 0.66861821]
 [0.81106372 0.73118198]]
[[0.38135421 0.69572593]
 [0.63159265 0.7650871 ]]

[[[[0.73360585 0.66861821]
   [0.30249323 0.83328309]]

  [[0.81106372 0.73118198]
   [0.41097539 1.14645662]]]


 [[[0.42249045 0.47534563]
   [0.38135421 0.69572593]]

  [[0.76114408 0.95473813]
   [0.63159265 0.7650871 ]]]]


##  Hadamard product (element-wise product)

Element-wise product or the Hadamard product:

\begin{align}
C = A \odot B
\end{align}

Use `*` operator in numpy.

In [5]:
A = np.arange(0, 12).reshape(4, 3)
B = np.arange(12, 24).reshape(4, 3)
print("A= "); print(A)
print("B= "); print(B)

A= 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
B= 
[[12 13 14]
 [15 16 17]
 [18 19 20]
 [21 22 23]]


In [6]:
C = A*B
print("C= "); print(C)

C= 
[[  0  13  28]
 [ 45  64  85]
 [108 133 160]
 [189 220 253]]


##  Square

Element-wise square of a matrix

\begin{align}
C = A^{2}
\end{align}

Use `A**2`, `np.square(A)`, `np.power(A, 2)` or `A*A` in numpy.

Note that

\begin{align}
A^{2} &\neq A \cdot A \\
A^{2} &\neq A^T \cdot A
\end{align}

Don't use `np.matmul` or `np.dot` for element-wise square computation.

In [7]:
A = np.arange(0, 12).reshape(4, 3)

C1 = A**2
C2 = np.square(A)
C3 = np.power(A, 2)
C4 = A*A

assert np.allclose(C1, C2)
assert np.allclose(C1, C3)
assert np.allclose(C1, C4)

print("A= "); print(A)
print("C= "); print(C1)

A= 
[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
C= 
[[  0   1   4]
 [  9  16  25]
 [ 36  49  64]
 [ 81 100 121]]


## Kronecker product (matrix direct product)

\begin{align}
C = A \otimes B
\end{align}

In [8]:
A = np.array([[1, 2],[3, 4]])
B = np.arange(0, 9).reshape(3, 3)
print("A= "); print(A)
print("B= "); print(B)

A= 
[[1 2]
 [3 4]]
B= 
[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [9]:
C = np.kron(A, B)
print("C= "); print(C)

C= 
[[ 0  1  2  0  2  4]
 [ 3  4  5  6  8 10]
 [ 6  7  8 12 14 16]
 [ 0  3  6  0  4  8]
 [ 9 12 15 12 16 20]
 [18 21 24 24 28 32]]
